//
// Created by 310165137 on 19/10/2020.
//

#ifndef PARALLELMERGESORT_PARALLELMERGESORT_H
#define PARALLELMERGESORT_PARALLELMERGESORT_H


#define UPPER_RANGE (1000)
#define LOWER_RANGE (-1000)

#endif //PARALLELMERGESORT_PARALLELMERGESORT_H
